#!/usr/bin/env python

from sys import argv
from sploitego.commands.debug_transform import run

__author__ = 'Nadeem Douba'
__copyright__ = 'Copyright 2012, Sploitego Project'
__credits__ = []

__license__ = 'GPL'
__version__ = '0.1'
__maintainer__ = 'Nadeem Douba'
__email__ = 'ndouba@gmail.com'
__status__ = 'Development'


if __name__ == '__main__':
    run(argv[1:])