#!/usr/bin/env python

from pkg_resources import resource_filename
from string import Template
from getpass import getuser
from os import path, sep
from sys import argv
from re import sub


__author__ = 'Nadeem Douba'
__copyright__ = 'Copyright 2012, Sploitego Project'
__credits__ = ['Nadeem Douba']

__license__ = 'GPL'
__version__ = '0.1'
__maintainer__ = 'Nadeem Douba'
__email__ = 'ndouba@gmail.com'
__status__ = 'Development'


def read(f, kw):
    t = Template(file(resource_filename('sploitego.resources.template', '%s.plate' % f)).read())
    return t.substitute(**kw)


def write(f, s):
    print 'creating file %s...' % f
    w = file(f, mode='wb')
    w.write(s)
    w.close()


def main():

    if not argv[1:]:
        print 'usage: %s <transform name> [transform dir]' % argv[0]
        exit(-1)
    elif not argv[2:] and not path.exists('__init__.py'):
        print 'Current directory does not appear to be a python package directory... quitting!'
        print 'usage: %s <transform name> [transform dir]' % argv[0]
        exit(-1)

    s = argv[1]
    d = './' if not argv[2:] else argv[2]
    kw = {
        'author' : getuser(),
        'year' : 2012
    }

    write(sep.join([d, s if s.endswith('.py') else '%s.py' % s ]), read('newtransform', kw))

    print 'installing to __init__.py'
    d = file('__init__.py').read()
    file('__init__.py', mode='wb').write(sub(r'__all__\s*\=\s*\[', '__all__ = [\n    %s,' % repr(s), d))
    print 'done!'

if __name__ == '__main__':
    main()