#!/usr/bin/env python


import sys
from zipfile import ZipFile
from sploitego.xmltools.objectify import objectify


__author__ = 'Nadeem Douba'
__copyright__ = 'Copyright 2012, Sploitego Project'
__credits__ = ['Nadeem Douba']

__license__ = 'GPL'
__version__ = '0.1'
__maintainer__ = 'Nadeem Douba'
__email__ = 'ndouba@gmail.com'
__status__ = 'Development'



def main(*args):

    if len(args) == 1:
        print 'usage: %s <graph.mtgx>' % args[0]
        sys.exit(-1)

    zip = ZipFile(args[1])
    graphs = filter(lambda x: x.endswith('.graphml'), zip.namelist())

    for f in graphs:
        csv = open(f.split('/')[1].split('.')[0] + '.csv', 'w')
        xml = zip.open(f).read()
        o = objectify(xml)
        for node in o.graph.node:
            for d in node.data:
                if 'MaltegoEntity' in d:
                    csv.write(('"Entity Type=%s",' % d.MaltegoEntity.type).strip())
                    for prop in d.MaltegoEntity.Properties.Property:
                        if '"' in prop.Value:
                            prop.Value.replace('"', '""')
                        csv.write(('"%s=%s",' % (prop.displayName, prop.Value)).strip())
                    csv.write('\n')


if __name__ == '__main__':
    main(*sys.argv)