#!/usr/bin/env python

import sys

from sploitego.transforms.common.msfrpcd import login
from sploitego.msftools.shell import launch

__author__ = 'Nadeem Douba'
__copyright__ = 'Copyright 2012, Sploitego Project'
__credits__ = []

__license__ = 'GPL'
__version__ = '0.1'
__maintainer__ = 'Nadeem Douba'
__email__ = 'ndouba@gmail.com'
__status__ = 'Development'


if __name__ == '__main__':

    m = login(host=sys.argv[1], port=sys.argv[2], uri=sys.argv[3])
    if m is None:
        exit(0)
    launch(m, sessionid=int(sys.argv[4]))